{ config, pkgs, ... }:

{
  programs.fish = {
    enable = true;
    greeting = ''
      cbonsai -m "Hewwow :3" -M 12 -L 40 -p
    '';

    shellAliases = {
      cd = "z";
    };

    interactiveShellInit = ''
      # Initialize zoxide
      zoxide init fish | source

      # Source the theme file generated by wallust
      # This file sets the prompt colors
      source ${config.home.homeDirectory}/.config/fish/themes/fishcolors.theme
    '';
  };

  programs.zoxide.enable = true;
}
