{ config, pkgs, ... }:

{

  programs.wallust = {
    enable = true;
    settings = {
      backend = "full";
      color_space = "lch";
      palette = "dark16";
      check_contrast = true;
      saturation = 40;

      templates = {
        hypr = { template = "hyprcolor.conf"; target = "~/.config/hypr/hyprcolor.conf"; };
        waybar = { template = "waybar.css"; target = "~/.config/waybar/waybar.css"; };
        kitty = { template = "kittycolors.conf"; target = "~/.config/kitty/themes/kittycolors.conf"; };
        rofi = { template = "roficolors.rasi"; target = "~/.config/rofi/themes/roficolors.rasi"; };
        cava = { template = "cavacolors.ini"; target = "~/.config/cava/config"; };
        btop = { template = "btopcolor.theme"; target = "~/.config/btop/themes/btopcolor.theme"; };
      };
    };
  };


  xdg.configFile = {
    "wallust/templates/hyprcolor.conf".text = ''
      # Sourced by hyprland.conf
      # Generated by wallust

      general {
        col.active_border = rgba({color1.rgb_hex}{color0.alpha_hex}) rgba({color2.rgb_hex}{color0.alpha_hex}) 45deg
        col.inactive_border = rgba({color0.rgb_hex}aa)
      }
    '';

    "wallust/templates/waybar.css".text = ''
      /* Generated by wallust */
      * {
          border: none;
          font-family: JetBrainsMono Nerd Font;
          font-weight: bold;
          font-size: 10pt;
          min-height: 10px;
      }

      window#waybar {
          background: rgba({color0.rgb_hex}, 0.5);
          color: #{color7.rgb_hex};
      }

      #workspaces button {
          padding: 0 5px;
          background: transparent;
          color: #{color7.rgb_hex};
          border-bottom: 2px solid transparent;
      }

      #workspaces button.focused {
          color: #{color1.rgb_hex};
          border-bottom: 2px solid #{color1.rgb_hex};
      }
    '';

    "wallust/templates/kittycolors.conf".text = ''
      ## Generated by wallust
      foreground #{color7.rgb_hex}
      background #{color0.rgb_hex}
      cursor #{color7.rgb_hex}
      selection_foreground #{color0.rgb_hex}
      selection_background #{color7.rgb_hex}

      # Black
      color0 #{color0.rgb_hex}
      color8 #{color8.rgb_hex}

      # Red
      color1 #{color1.rgb_hex}
      color9 #{color9.rgb_hex}

      # Green
      color2 #{color2.rgb_hex}
      color10 #{color10.rgb_hex}

      # Yellow
      color3 #{color3.rgb_hex}
      color11 #{color11.rgb_hex}

      # Blue
      color4 #{color4.rgb_hex}
      color12 #{color12.rgb_hex}

      # Magenta
      color5 #{color5.rgb_hex}
      color13 #{color13.rgb_hex}

      # Cyan
      color6 #{color6.rgb_hex}
      color14 #{color14.rgb_hex}

      # White
      color7 #{color7.rgb_hex}
      color15 #{color15.rgb_hex}
    '';

    "wallust/templates/roficolors.rasi".text = ''
      /* Generated by wallust */
      * {
          background-color: #{color0.rgb_hex};
          text-color: #{color7.rgb_hex};
          border-color: #{color1.rgb_hex};
          font: "JetBrainsMono Nerd Font 12";
      }

      window {
          width: 30%;
          border: 2px;
          border-radius: 10px;
      }

      inputbar {
          children: [prompt, entry];
          padding: 8px;
          border-radius: 5px;
          background-color: #{color8.rgb_hex};
      }

      prompt, entry {
          text-color: #{color7.rgb_hex};
      }

      listview {
          padding: 8px;
      }

      element {
          padding: 8px;
          border-radius: 5px;
      }

      element-text {
          background-color: inherit;
          text-color: inherit;
      }

      element.selected {
          background-color: #{color1.rgb_hex};
          text-color: #{color0.rgb_hex};
      }
    '';

    "wallust/templates/cavacolors.ini".text = ''
      [general]
      framerate = 60
      autosens = 1
      sensitivity = 75
      bars = 16
      bar_width = 4
      bar_spacing = 2

      [input]
      method = pulse
      source = auto

      [output]
      method = noncurses
      channels = stereo
      mono_option = average
      reverse = 0

      [color]
      foreground = '#{color1.rgb_hex}'
      gradient = 1
      gradient_count = 2
      gradient_color_1 = '#{color2.rgb_hex}'
      gradient_color_2 = '#{color4.rgb_hex}'

      [smoothing]
      noise_reduction = 0.77
    '';

    "wallust/templates/btopcolor.theme".text = ''
      # btop theme generated by wallust
      theme[main_bg]="#{color0.rgb_hex}"
      theme[main_fg]="#{color7.rgb_hex}"
      theme[title]="#{color7.rgb_hex}"
      theme[hi_fg]="#{color1.rgb_hex}"
      theme[selected_bg]="#{color8.rgb_hex}"
      theme[selected_fg]="#{color1.rgb_hex}"
      theme[inactive_fg]="#{color8.rgb_hex}"
      theme[graph_text]="#{color8.rgb_hex}"
      theme[meter_bg]="#{color8.rgb_hex}"
      theme[proc_misc]="#{color4.rgb_hex}"
      theme[cpu_box]="#{color2.rgb_hex}"
      theme[mem_box]="#{color4.rgb_hex}"
      theme[net_box]="#{color5.rgb_hex}"
      theme[proc_box]="#{color3.rgb_hex}"
      theme[div_line]="#{color8.rgb_hex}"
      theme[cpu_start]="#{color2.rgb_hex}"
      theme[cpu_mid]="#{color3.rgb_hex}"
      theme[cpu_end]="#{color1.rgb_hex}"
      theme[free_start]="#{color8.rgb_hex}"
      theme[free_mid]="#{color8.rgb_hex}"
      theme[free_end]="#{color8.rgb_hex}"
      theme[cached_start]="#{color3.rgb_hex}"
      theme[cached_mid]="#{color3.rgb_hex}"
      theme[cached_end]="#{color3.rgb_hex}"
      theme[available_start]="#{color2.rgb_hex}"
      theme[available_mid]="#{color2.rgb_hex}"
      theme[available_end]="#{color2.rgb_hex}"
      theme[used_start]="#{color4.rgb_hex}"
      theme[used_mid]="#{color4.rgb_hex}"
      theme[used_end]="#{color4.rgb_hex}"
      theme[download_start]="#{color5.rgb_hex}"
      theme[download_mid]="#{color5.rgb_hex}"
      theme[download_end]="#{color5.rgb_hex}"
      theme[upload_start]="#{color6.rgb_hex}"
      theme[upload_mid]="#{color6.rgb_hex}"
      theme[upload_end]="#{color6.rgb_hex}"
      theme[process_start]="#{color1.rgb_hex}"
      theme[process_mid]="#{color3.rgb_hex}"
      theme[process_end]="#{color4.rgb_hex}"
    '';
  };
}
